packages:
  - "packages/*"
  - "examples/*"
  - "benchmarks/*"
  - "site"

overrides:
  "eslint-config-setup>eslint-plugin-oxlint": "1.75.0"
  "waku>vite": "^8.0.16"
  "waku>@vitejs/plugin-react": "^6.0.1"

peerDependencyRules:
  allowedVersions:
    "eslint-plugin-jsx-a11y>eslint": "^10.0.0"

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - sharp
allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@oxc-parser/binding-android-arm-eabi@0.132.0"
  - "@oxc-parser/binding-android-arm64@0.132.0"
  - "@oxc-parser/binding-darwin-arm64@0.132.0"
  - "@oxc-parser/binding-darwin-x64@0.132.0"
  - "@oxc-parser/binding-freebsd-x64@0.132.0"
  - "@oxc-parser/binding-linux-arm-gnueabihf@0.132.0"
  - "@oxc-parser/binding-linux-arm-musleabihf@0.132.0"
  - "@oxc-parser/binding-linux-arm64-gnu@0.132.0"
  - "@oxc-parser/binding-linux-arm64-musl@0.132.0"
  - "@oxc-parser/binding-linux-ppc64-gnu@0.132.0"
  - "@oxc-parser/binding-linux-riscv64-gnu@0.132.0"
  - "@oxc-parser/binding-linux-riscv64-musl@0.132.0"
  - "@oxc-parser/binding-linux-s390x-gnu@0.132.0"
  - "@oxc-parser/binding-linux-x64-gnu@0.132.0"
  - "@oxc-parser/binding-linux-x64-musl@0.132.0"
  - "@oxc-parser/binding-openharmony-arm64@0.132.0"
  - "@oxc-parser/binding-wasm32-wasi@0.132.0"
  - "@oxc-parser/binding-win32-arm64-msvc@0.132.0"
  - "@oxc-parser/binding-win32-ia32-msvc@0.132.0"
  - "@oxc-parser/binding-win32-x64-msvc@0.132.0"
  - "@oxc-project/types@0.132.0"
  - "@types/node@26.0.0"
  - oxc-parser@0.132.0
  - eslint@10.5.0
