declare module "virtual:palamedes/server-catalogs" {
  import type { CompiledCatalogMessages } from "@palamedes/core";

  /** Generated by the Vite plugin; applications never implement this module. */
  export function loadServerCatalog(locale: string): Promise<CompiledCatalogMessages>;
}
