import { createI18n, type CreateI18nOptions } from "@palamedes/core";
// Generated by the Vite plugin; never resolved in an application browser graph.
import { loadServerCatalog } from "virtual:palamedes/server-catalogs";

/** Load shared immutable content for one locale and create isolated request state. */
export async function createViteServerI18n(options: CreateI18nOptions & { locale: string }) {
  const messages = await loadServerCatalog(options.locale);
  const i18n = createI18n(options);
  i18n.load(options.locale, messages);
  return i18n;
}
