//! Native MDX analysis and JSX module lowering.
//!
//! FerroMark owns syntax recognition and exposes the versioned semantic event
//! stream. Palamedes consumes that stream to define translation units, rich
//! placeholders, message identity, extraction records, and the runtime module.

use std::collections::{BTreeMap, BTreeSet};

use ferromark::block::{CodeBlockKind, ListKind};
use ferromark::mdx::{parse_events_strict, MdxDiagnostic, MdxEvent};
use ferromark::{BlockEvent, InlineEvent, Range};
use serde::{Deserialize, Serialize};

use crate::extract::ExtractedMessageRecord;
use crate::icu_text::{compiled_message_key, escape_icu_literal, escape_icu_source_literal};
use crate::jsx_entities::decode_jsx_entities;
use crate::jsx_message::{clean_jsx_text, join_jsx_message_parts, JsxMessagePart};
use crate::source::{SourceLocator, SourceRange};
use crate::transform::NativeTransformSourceMap;

const DEFAULT_IGNORE_DIRECTIVE: &str = "palamedes-ignore";
const REACT_TRANS_MODULE: &str = "@palamedes/react/compiled";
const REACT_RUNTIME_MODULE: &str = "@palamedes/react/runtime";
const SOLID_TRANS_MODULE: &str = "@palamedes/solid/compiled";
const SOLID_RUNTIME_MODULE: &str = "@palamedes/solid/runtime";

/// Framework contract used for generated rich-text component bindings.
#[derive(Clone, Copy, Debug, Default, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum MdxFramework {
    /// React elements are passed as rich-text component templates.
    #[default]
    React,
    /// Solid receives child-wrapper functions for non-empty rich placeholders.
    Solid,
}

/// Shared extraction and compilation options for MDX.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(default, rename_all = "camelCase")]
pub struct MdxOptions {
    /// Framework module contract generated by the native compiler.
    pub framework: MdxFramework,
    /// Static JSX attributes whose values are user-facing.
    #[serde(alias = "translatable-attributes", alias = "translatable_attributes")]
    pub translatable_attributes: Vec<String>,
    /// Scalar front-matter fields whose values are user-facing.
    #[serde(alias = "front-matter-fields", alias = "front_matter_fields")]
    pub front_matter_fields: Vec<String>,
    /// Module exporting the framework's `Trans` component.
    #[serde(alias = "trans-module", alias = "trans_module")]
    pub trans_module: Option<String>,
    /// Module exporting the framework-aware `getI18n` accessor.
    #[serde(alias = "runtime-module", alias = "runtime_module")]
    pub runtime_module: Option<String>,
    /// Explicit opt-out marker used in an immediately preceding comment.
    #[serde(alias = "ignore-directive", alias = "ignore_directive")]
    pub ignore_directive: String,
    /// Preserve source messages as runtime fallbacks in generated modules.
    pub keep_source_fallbacks: bool,
}

impl Default for MdxOptions {
    fn default() -> Self {
        Self {
            framework: MdxFramework::React,
            translatable_attributes: vec!["alt".to_owned()],
            front_matter_fields: Vec::new(),
            trans_module: None,
            runtime_module: None,
            ignore_directive: DEFAULT_IGNORE_DIRECTIVE.to_owned(),
            keep_source_fallbacks: false,
        }
    }
}

impl MdxOptions {
    fn trans_module(&self) -> &str {
        self.trans_module
            .as_deref()
            .unwrap_or(match self.framework {
                MdxFramework::React => REACT_TRANS_MODULE,
                MdxFramework::Solid => SOLID_TRANS_MODULE,
            })
    }

    fn runtime_module(&self) -> &str {
        self.runtime_module
            .as_deref()
            .unwrap_or(match self.framework {
                MdxFramework::React => REACT_RUNTIME_MODULE,
                MdxFramework::Solid => SOLID_RUNTIME_MODULE,
            })
    }

    /// Stable cache stamp for semantics that affect extracted records.
    #[must_use]
    pub fn extraction_stamp(&self) -> String {
        let mut attributes = self.translatable_attributes.clone();
        attributes.sort();
        attributes.dedup();
        let mut fields = self.front_matter_fields.clone();
        fields.sort();
        fields.dedup();
        format!(
            "mdx-v1|attrs={}|front={}|ignore={}",
            attributes.join(","),
            fields.join(","),
            self.ignore_directive
        )
    }
}

/// Backward-compatible name for the shared source diagnostic range.
pub type MdxSourceRange = SourceRange;

/// Structured source-ranged MDX diagnostic.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MdxDiagnosticRecord {
    /// Stable FerroMark diagnostic code.
    pub code: String,
    /// Human-readable diagnostic text.
    pub message: String,
    /// Primary source location.
    pub primary: MdxSourceRange,
    /// Related source location for delimiter/tag mismatches.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub related: Option<MdxSourceRange>,
}

/// Coarse native MDX workflow result shared by extraction and Vite.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MdxAnalysisResult {
    /// Source-first messages derived from semantic units and configured fields.
    pub messages: Vec<ExtractedMessageRecord>,
    /// Structural diagnostics. Invalid input does not produce module code.
    pub diagnostics: Vec<MdxDiagnosticRecord>,
    /// Framework-compatible JSX module source.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Stable runtime IDs referenced by the generated module.
    pub compiled_ids: Vec<String>,
    /// Native source map for generated code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub map: Option<NativeTransformSourceMap>,
}

/// Analyze and compile an MDX document using one native semantic pipeline.
#[must_use]
pub fn analyze_mdx(source: &str, filename: &str, options: MdxOptions) -> MdxAnalysisResult {
    let stream = match parse_events_strict(source) {
        Ok(stream) => stream,
        Err(diagnostics) => {
            let locator = SourceLocator::new(source);
            return MdxAnalysisResult {
                messages: Vec::new(),
                diagnostics: diagnostics
                    .into_iter()
                    .map(|diagnostic| diagnostic_record(&locator, diagnostic))
                    .collect(),
                code: None,
                compiled_ids: Vec::new(),
                map: None,
            };
        }
    };

    if let Some(range) = unsupported_footnote_range(source, &stream.events) {
        let locator = SourceLocator::new(source);
        return MdxAnalysisResult {
            messages: Vec::new(),
            diagnostics: vec![MdxDiagnosticRecord {
                code: "UnsupportedFootnote".to_owned(),
                message: "footnotes are not supported by Palamedes MDX compilation yet".to_owned(),
                primary: source_range(&locator, range),
                related: None,
            }],
            code: None,
            compiled_ids: Vec::new(),
            map: None,
        };
    }

    let compiler = MdxCompiler::new(source, filename, options, &stream.link_references);
    compiler.compile(&stream.events)
}

/// Extract MDX messages without exposing host-side parser details.
///
/// Invalid structural MDX is returned as a readable error containing exact
/// line/column locations. Call [`analyze_mdx`] for typed diagnostics.
pub fn extract_mdx_messages(
    source: &str,
    filename: &str,
    options: MdxOptions,
) -> Result<Vec<ExtractedMessageRecord>, String> {
    let result = analyze_mdx(source, filename, options);
    if result.diagnostics.is_empty() {
        Ok(result.messages)
    } else {
        Err(result
            .diagnostics
            .iter()
            .map(|diagnostic| {
                format!(
                    "{}:{}:{}: {} ({})",
                    filename,
                    diagnostic.primary.line,
                    diagnostic.primary.column,
                    diagnostic.message,
                    diagnostic.code
                )
            })
            .collect::<Vec<_>>()
            .join("\n"))
    }
}

fn diagnostic_record(locator: &SourceLocator, diagnostic: MdxDiagnostic) -> MdxDiagnosticRecord {
    MdxDiagnosticRecord {
        code: format!("{:?}", diagnostic.code),
        message: diagnostic.message.to_owned(),
        primary: source_range(locator, diagnostic.primary_range),
        related: diagnostic
            .related_range
            .map(|range| source_range(locator, range)),
    }
}

fn source_range(locator: &SourceLocator, range: Range) -> MdxSourceRange {
    locator.range(range.start_usize(), range.end_usize())
}

#[derive(Debug)]
struct MessageReference {
    message: String,
    id: String,
}

fn runtime_lookup_arguments(reference: &MessageReference, keep_source_fallbacks: bool) -> String {
    if keep_source_fallbacks {
        format!(
            "{}, undefined, {{ message: {} }}",
            js_string(&reference.id),
            js_string(&reference.message)
        )
    } else {
        js_string(&reference.id)
    }
}

struct MdxCompiler<'a> {
    source: &'a str,
    filename: &'a str,
    options: MdxOptions,
    link_references: &'a [ferromark::LinkRefDef],
    locator: SourceLocator<'a>,
    body: ModuleWriter,
    esm: Vec<(usize, String)>,
    messages: Vec<ExtractedMessageRecord>,
    compiled_ids: Vec<String>,
    front_matter: BTreeMap<String, String>,
    translated_front_matter: BTreeMap<String, MessageReference>,
    needs_trans: bool,
    needs_i18n: bool,
    unit: Option<RichUnit>,
    code_block_depth: usize,
    table_head_depth: usize,
}

impl<'a> MdxCompiler<'a> {
    fn new(
        source: &'a str,
        filename: &'a str,
        options: MdxOptions,
        link_references: &'a [ferromark::LinkRefDef],
    ) -> Self {
        Self {
            source,
            filename,
            options,
            link_references,
            locator: SourceLocator::new(source),
            body: ModuleWriter::default(),
            esm: Vec::new(),
            messages: Vec::new(),
            compiled_ids: Vec::new(),
            front_matter: BTreeMap::new(),
            translated_front_matter: BTreeMap::new(),
            needs_trans: false,
            needs_i18n: false,
            unit: None,
            code_block_depth: 0,
            table_head_depth: 0,
        }
    }

    fn compile(mut self, events: &[MdxEvent]) -> MdxAnalysisResult {
        for event in events {
            self.event(event);
        }
        self.finish_unit();

        let mut writer = ModuleWriter::default();
        for (offset, source) in &self.esm {
            writer.append_at(source, *offset);
            if !source.ends_with('\n') {
                writer.append("\n");
            }
        }
        if self.needs_trans {
            writer.append(&format!(
                "import {{ Trans as __PalamedesTrans }} from {};\n",
                js_string(self.options.trans_module())
            ));
        }
        if self.needs_i18n {
            writer.append(&format!(
                "import {{ getI18n as __palamedesGetI18n }} from {};\n",
                js_string(self.options.runtime_module())
            ));
        }
        self.emit_front_matter(&mut writer);
        writer.append("\nfunction MDXContent() {\n");
        writer.append("  return (\n    <>\n");
        writer.append_writer(&self.body, "      ");
        writer.append("    </>\n  );\n}\n\nexport default MDXContent;\n");

        let code = writer.code;
        let map = NativeTransformSourceMap {
            version: 3,
            sources: vec![self.filename.to_owned()],
            sources_content: Some(vec![Some(self.source.to_owned())]),
            names: Vec::new(),
            mappings: encode_mappings(&writer.anchors, self.source),
            file: Some(self.filename.to_owned()),
        };

        MdxAnalysisResult {
            messages: self.messages,
            diagnostics: Vec::new(),
            code: Some(code),
            compiled_ids: self.compiled_ids,
            map: Some(map),
        }
    }

    fn event(&mut self, event: &MdxEvent) {
        match event {
            MdxEvent::FrontMatter { content, .. } => self.front_matter(*content),
            MdxEvent::Esm(range) => self.esm.push((
                range.start_usize(),
                range_text(self.source, *range).to_owned(),
            )),
            MdxEvent::FlowExpression(range) => {
                self.finish_unit();
                let expression = range_text(self.source, *range).trim();
                self.body.append_at(expression, range.start_usize());
                self.body.append("\n");
            }
            MdxEvent::FlowJsxOpen(range) | MdxEvent::FlowJsxSelfClose(range) => {
                self.finish_unit();
                let markup = self.rewrite_jsx_tag(*range);
                self.body.append_at(markup.trim(), range.start_usize());
                self.body.append("\n");
            }
            MdxEvent::FlowJsxClose(range) => {
                self.finish_unit();
                self.body
                    .append_at(range_text(self.source, *range).trim(), range.start_usize());
                self.body.append("\n");
            }
            MdxEvent::Block(event) => self.block_event(event),
            MdxEvent::Inline(event) => self.inline_event(event),
        }
    }

    fn front_matter(&mut self, content: Range) {
        for scalar in parse_front_matter_scalars(self.source, content) {
            self.front_matter
                .insert(scalar.key.clone(), scalar.value.clone());
            if self
                .options
                .front_matter_fields
                .iter()
                .any(|field| field == &scalar.key)
                && !scalar.value.is_empty()
            {
                let reference =
                    self.push_message(scalar.value, BTreeMap::new(), scalar.value_offset);
                self.translated_front_matter.insert(scalar.key, reference);
                self.needs_i18n = true;
            }
        }
    }

    fn emit_front_matter(&self, writer: &mut ModuleWriter) {
        if self.front_matter.is_empty() {
            return;
        }
        writer.append("\nexport const frontmatter = ");
        writer.append(
            &serde_json::to_string(&self.front_matter)
                .expect("front matter scalar map must serialize"),
        );
        writer.append(";\n");
        if self.translated_front_matter.is_empty() {
            return;
        }

        writer.append("export function getTranslatedFrontmatter() {\n");
        writer.append("  const __i18n = __palamedesGetI18n();\n");
        writer.append("  return { ...frontmatter");
        for (key, reference) in &self.translated_front_matter {
            writer.append(&format!(
                ", {}: __i18n._({})",
                js_string(key),
                runtime_lookup_arguments(reference, self.options.keep_source_fallbacks)
            ));
        }
        writer.append(" };\n}\n");
    }

    fn block_event(&mut self, event: &BlockEvent) {
        match event {
            BlockEvent::ParagraphStart => {
                self.finish_unit();
                self.start_unit("<p>");
            }
            BlockEvent::ParagraphEnd => {
                if self.finish_unit() {
                    self.body.append("</p>\n");
                }
            }
            BlockEvent::HeadingStart { level } => {
                self.finish_unit();
                self.start_unit(&format!("<h{level}>"));
            }
            BlockEvent::HeadingEnd { level } => {
                if self.finish_unit() {
                    self.body.append(&format!("</h{level}>\n"));
                }
            }
            BlockEvent::CodeBlockStart { kind } => {
                self.finish_unit();
                self.code_block_depth += 1;
                let class_name = match kind {
                    CodeBlockKind::Fenced { info: Some(info) } => range_text(self.source, *info)
                        .split_whitespace()
                        .next()
                        .filter(|language| !language.is_empty())
                        .map(|language| format!("language-{language}")),
                    CodeBlockKind::Fenced { info: None } | CodeBlockKind::Indented => None,
                };
                match class_name {
                    Some(class_name) => self.body.append(&format!(
                        "<pre><code className={{{}}}>",
                        js_string(&class_name)
                    )),
                    None => self.body.append("<pre><code>"),
                }
            }
            BlockEvent::CodeBlockEnd => {
                self.code_block_depth = self.code_block_depth.saturating_sub(1);
                self.body.append("</code></pre>\n");
            }
            BlockEvent::BlockQuoteStart { .. } => {
                self.finish_unit();
                self.body.append("<blockquote>\n");
            }
            BlockEvent::BlockQuoteEnd => {
                self.finish_unit();
                self.body.append("</blockquote>\n");
            }
            BlockEvent::ListStart { kind, .. } => {
                self.finish_unit();
                match kind {
                    ListKind::Unordered => self.body.append("<ul>\n"),
                    ListKind::Ordered { start, .. } if *start == 1 => self.body.append("<ol>\n"),
                    ListKind::Ordered { start, .. } => {
                        self.body.append(&format!("<ol start={{{start}}}>\n"));
                    }
                }
            }
            BlockEvent::ListEnd { kind, .. } => {
                self.finish_unit();
                match kind {
                    ListKind::Unordered => self.body.append("</ul>\n"),
                    ListKind::Ordered { .. } => self.body.append("</ol>\n"),
                }
            }
            BlockEvent::ListItemStart { .. } => {
                self.finish_unit();
                self.body.append("<li>");
            }
            BlockEvent::ListItemEnd => {
                self.finish_unit();
                self.body.append("</li>\n");
            }
            BlockEvent::DefinitionListStart => self.body.append("<dl>\n"),
            BlockEvent::DefinitionListEnd => self.body.append("</dl>\n"),
            BlockEvent::DefinitionTermStart => {
                self.finish_unit();
                self.start_unit("<dt>");
            }
            BlockEvent::DefinitionTermEnd => {
                if self.finish_unit() {
                    self.body.append("</dt>\n");
                }
            }
            BlockEvent::DefinitionDescriptionStart { .. } => {
                self.finish_unit();
                self.start_unit("<dd>");
            }
            BlockEvent::DefinitionDescriptionEnd => {
                if self.finish_unit() {
                    self.body.append("</dd>\n");
                }
            }
            BlockEvent::ThematicBreak(range) => {
                self.finish_unit();
                self.body.append_at("<hr />\n", range.start_usize());
            }
            BlockEvent::Comment(_) => {}
            BlockEvent::HtmlBlockStart | BlockEvent::HtmlBlockEnd => {}
            BlockEvent::HtmlBlockText(range) => {
                let html = range_text(self.source, *range);
                if is_html_comment(html) {
                    return;
                }
                self.finish_unit();
                self.body
                    .append_at(&format!("{{{}}}", js_string(html)), range.start_usize());
            }
            BlockEvent::SoftBreak => {
                if let Some(unit) = self.unit.as_mut() {
                    unit.push(RichNode::Text(" ".to_owned(), None));
                }
            }
            BlockEvent::Text(range) => {
                self.mark_unit_start(range.start_usize());
                if let Some(unit) = self.unit.as_mut() {
                    unit.text(self.source, *range);
                }
            }
            BlockEvent::Code(range) => {
                self.finish_unit();
                self.body.append_at(
                    &format!("{{{}}}", js_string(range_text(self.source, *range))),
                    range.start_usize(),
                );
            }
            BlockEvent::VirtualSpaces(count) => {
                if self.code_block_depth > 0 {
                    self.body
                        .append(&format!("{{{}}}", js_string(&" ".repeat(*count as usize))));
                }
            }
            BlockEvent::TableStart => self.body.append("<table>\n"),
            BlockEvent::TableColumnWidthsStart
            | BlockEvent::TableColumnWidth { .. }
            | BlockEvent::TableColumnWidthsEnd => {}
            BlockEvent::TableEnd => self.body.append("</table>\n"),
            BlockEvent::TableHeadStart => {
                self.table_head_depth += 1;
                self.body.append("<thead>\n");
            }
            BlockEvent::TableHeadEnd => {
                self.table_head_depth = self.table_head_depth.saturating_sub(1);
                self.body.append("</thead>\n");
            }
            BlockEvent::TableBodyStart => self.body.append("<tbody>\n"),
            BlockEvent::TableBodyEnd => self.body.append("</tbody>\n"),
            BlockEvent::TableRowStart => self.body.append("<tr>"),
            BlockEvent::TableRowEnd => self.body.append("</tr>\n"),
            BlockEvent::TableCellStart { alignment, colspan } => {
                self.finish_unit();
                let tag = if self.table_head_depth > 0 {
                    "th"
                } else {
                    "td"
                };
                let mut attrs = String::new();
                if *colspan > 1 {
                    attrs.push_str(&format!(" colSpan={{{colspan}}}"));
                }
                let alignment = match alignment {
                    ferromark::Alignment::None => None,
                    ferromark::Alignment::Left => Some("left"),
                    ferromark::Alignment::Center => Some("center"),
                    ferromark::Alignment::Right => Some("right"),
                };
                if let Some(alignment) = alignment {
                    attrs.push_str(&format!(" align={{{}}}", js_string(alignment)));
                }
                self.start_unit(&format!("<{tag}{attrs}>"));
            }
            BlockEvent::TableCellEnd => {
                let tag = if self.table_head_depth > 0 {
                    "th"
                } else {
                    "td"
                };
                if self.finish_unit() {
                    self.body.append(&format!("</{tag}>"));
                }
            }
        }
    }

    fn start_unit(&mut self, opening: &str) {
        let checkpoint = self.body.checkpoint();
        self.body.append(opening);
        self.unit = Some(RichUnit::new(checkpoint));
    }

    fn mark_unit_start(&mut self, source_offset: usize) {
        let Some(unit) = self.unit.as_mut() else {
            return;
        };
        if unit.source_offset.is_none() {
            unit.source_offset = Some(source_offset);
        }
        if unit.ignored.is_none() {
            unit.ignored = Some(is_ignored_unit(
                self.source,
                source_offset,
                &self.options.ignore_directive,
            ));
        }
    }

    fn inline_event(&mut self, event: &InlineEvent) {
        if self.unit.is_none() {
            return;
        }
        match event {
            InlineEvent::Text(range) => {
                self.mark_unit_start(range.start_usize());
                self.unit
                    .as_mut()
                    .expect("unit exists")
                    .text(self.source, *range);
            }
            InlineEvent::Code(range) => {
                self.mark_unit_start(range.start_usize());
                let code = range_text(self.source, *range);
                let markup = format!("<code>{{{}}}</code>", js_string(code));
                self.unit
                    .as_mut()
                    .expect("unit exists")
                    .push(RichNode::fixed(markup, range.start_usize()));
            }
            InlineEvent::EmphasisStart => self.open_markdown_component("<em>", "</em>"),
            InlineEvent::EmphasisEnd => self.close_component(),
            InlineEvent::StrongStart => self.open_markdown_component("<strong>", "</strong>"),
            InlineEvent::StrongEnd => self.close_component(),
            InlineEvent::StrikethroughStart => self.open_markdown_component("<del>", "</del>"),
            InlineEvent::StrikethroughEnd => self.close_component(),
            InlineEvent::SubscriptStart => self.open_markdown_component("<sub>", "</sub>"),
            InlineEvent::SubscriptEnd => self.close_component(),
            InlineEvent::SuperscriptStart => self.open_markdown_component("<sup>", "</sup>"),
            InlineEvent::SuperscriptEnd => self.close_component(),
            InlineEvent::HighlightStart => self.open_markdown_component("<mark>", "</mark>"),
            InlineEvent::HighlightEnd => self.close_component(),
            InlineEvent::LinkStart { url, .. } => {
                self.mark_unit_start(url.start_usize());
                let href = range_text(self.source, *url);
                self.open_markdown_component(&format!("<a href={{{}}}>", js_string(href)), "</a>");
            }
            InlineEvent::LinkStartRef { def_index } => {
                let href = self
                    .link_references
                    .get(*def_index as usize)
                    .and_then(|definition| std::str::from_utf8(&definition.url).ok())
                    .unwrap_or_default();
                self.open_markdown_component(&format!("<a href={{{}}}>", js_string(href)), "</a>");
            }
            InlineEvent::LinkEnd => self.close_component(),
            InlineEvent::ImageStart { url, .. } => {
                self.mark_unit_start(url.start_usize());
                let src = range_text(self.source, *url).to_owned();
                self.unit
                    .as_mut()
                    .expect("unit exists")
                    .open_image(src, url.start_usize());
            }
            InlineEvent::ImageStartRef { def_index } => {
                let src = self
                    .link_references
                    .get(*def_index as usize)
                    .and_then(|definition| std::str::from_utf8(&definition.url).ok())
                    .unwrap_or_default()
                    .to_owned();
                self.unit.as_mut().expect("unit exists").open_image(src, 0);
            }
            InlineEvent::ImageEnd => self.close_image(),
            InlineEvent::Autolink { url, .. } | InlineEvent::AutolinkLiteral { url, .. } => {
                self.mark_unit_start(url.start_usize());
                let href = range_text(self.source, *url);
                let markup = format!("<a href={{{0}}}>{{{0}}}</a>", js_string(href));
                self.unit
                    .as_mut()
                    .expect("unit exists")
                    .push(RichNode::fixed(markup, url.start_usize()));
            }
            InlineEvent::Html(range) => {
                let html = range_text(self.source, *range);
                if is_html_comment(html) {
                    return;
                }
                self.mark_unit_start(range.start_usize());
                self.unit
                    .as_mut()
                    .expect("unit exists")
                    .push(RichNode::fixed(
                        format!("{{{}}}", js_string(html)),
                        range.start_usize(),
                    ));
            }
            InlineEvent::SoftBreak => self
                .unit
                .as_mut()
                .expect("unit exists")
                .push(RichNode::Text(" ".to_owned(), None)),
            InlineEvent::HardBreak => self
                .unit
                .as_mut()
                .expect("unit exists")
                .push(RichNode::fixed("<br />".to_owned(), 0)),
            InlineEvent::EscapedChar(value) => self
                .unit
                .as_mut()
                .expect("unit exists")
                .push(RichNode::Text(char::from(*value).to_string(), None)),
            InlineEvent::FootnoteRef { .. } => {}
            InlineEvent::InlineFootnote(range)
            | InlineEvent::MathInline(range)
            | InlineEvent::MathDisplay(range) => {
                let content = range_text(self.source, *range);
                let markup = format!("<code>{{{}}}</code>", js_string(content));
                self.unit
                    .as_mut()
                    .expect("unit exists")
                    .push(RichNode::fixed(markup, range.start_usize()));
            }
            InlineEvent::MdxExpression(range) => {
                let raw = range_text(self.source, *range);
                if is_jsx_comment(raw) {
                    return;
                }
                self.mark_unit_start(range.start_usize());
                let expression = raw
                    .strip_prefix('{')
                    .and_then(|value| value.strip_suffix('}'))
                    .unwrap_or(raw)
                    .trim();
                if expression.is_empty() {
                    return;
                }
                self.unit
                    .as_mut()
                    .expect("unit exists")
                    .value(expression, range.start_usize());
            }
            InlineEvent::MdxJsxOpen(range) => {
                self.mark_unit_start(range.start_usize());
                let markup = self.rewrite_jsx_tag(*range);
                let name = ferromark::mdx::jsx_tag::parse_jsx_tag(markup.as_bytes())
                    .map(|tag| tag.name.to_owned())
                    .unwrap_or_default();
                if name.is_empty() {
                    self.unit.as_mut().expect("unit exists").open_transparent();
                } else {
                    self.unit.as_mut().expect("unit exists").open_component(
                        markup.trim().to_owned(),
                        format!("</{name}>"),
                        range.start_usize(),
                    );
                }
            }
            InlineEvent::MdxJsxClose(_) => self.close_component(),
            InlineEvent::MdxJsxSelfClose(range) => {
                self.mark_unit_start(range.start_usize());
                let markup = self.rewrite_jsx_tag(*range);
                self.unit
                    .as_mut()
                    .expect("unit exists")
                    .push(RichNode::fixed(
                        markup.trim().to_owned(),
                        range.start_usize(),
                    ));
            }
        }
    }

    fn open_markdown_component(&mut self, opening: &str, closing: &str) {
        self.unit.as_mut().expect("unit exists").open_component(
            opening.to_owned(),
            closing.to_owned(),
            0,
        );
    }

    fn close_component(&mut self) {
        self.unit.as_mut().expect("unit exists").close_frame();
    }

    fn close_image(&mut self) {
        let Some(mut unit) = self.unit.take() else {
            return;
        };
        let Some(image) = unit.close_image() else {
            self.unit = Some(unit);
            return;
        };
        let source_offset = image
            .children
            .iter()
            .find_map(RichNode::source_offset)
            .unwrap_or(image.source_offset);
        let alt = plain_text(&image.children);
        let ignored = unit.ignored.unwrap_or_else(|| {
            is_ignored_unit(self.source, source_offset, &self.options.ignore_directive)
        });
        let alt_reference = (!ignored && !alt.is_empty())
            .then(|| self.push_message(alt.clone(), BTreeMap::new(), source_offset));
        let alt_expression = alt_reference.as_ref().map_or_else(
            || js_string(&alt),
            |reference| {
                self.needs_i18n = true;
                format!(
                    "__palamedesGetI18n()._({})",
                    runtime_lookup_arguments(reference, self.options.keep_source_fallbacks)
                )
            },
        );
        let markup = format!(
            "<img src={{{}}} alt={{{alt_expression}}} />",
            js_string(&image.src),
        );
        unit.push(RichNode::fixed(markup, source_offset));
        self.unit = Some(unit);
    }

    fn finish_unit(&mut self) -> bool {
        let Some(mut unit) = self.unit.take() else {
            return false;
        };
        unit.close_all();
        if unit.roots.is_empty() {
            self.body.restore(unit.body_checkpoint);
            return false;
        }
        let source_offset = unit.source_offset.unwrap_or(0);
        let ignored = unit.ignored.unwrap_or_else(|| {
            is_ignored_unit(self.source, source_offset, &self.options.ignore_directive)
        });
        if ignored {
            self.body
                .append_at(&fallback_jsx(&unit.roots), source_offset);
            return true;
        }

        let mut components = Vec::new();
        let mut next_component = 0usize;
        let joined = rich_message(
            &unit.roots,
            self.options.framework,
            IcuLiteralTarget::Runtime,
            true,
            &mut next_component,
            &mut components,
        );
        if joined.message.trim().is_empty() || plain_text(&unit.roots).trim().is_empty() {
            self.body
                .append_at(&fallback_jsx(&unit.roots), source_offset);
            return true;
        }

        let mut ignored_source_components = Vec::new();
        let mut source_component_index = 0usize;
        let source_joined = rich_message(
            &unit.roots,
            self.options.framework,
            IcuLiteralTarget::Catalog,
            false,
            &mut source_component_index,
            &mut ignored_source_components,
        );
        let reference = self.push_message_with_runtime(
            source_joined.message,
            joined.message,
            unit.values.clone(),
            source_offset,
        );
        self.needs_trans = true;
        let mut props = vec![format!("id={{{}}}", js_string(&reference.id))];
        if self.options.keep_source_fallbacks {
            props.push(format!("message={{{}}}", js_string(&reference.message)));
        }
        if !unit.values.is_empty() {
            let values = unit
                .values
                .iter()
                .map(|(name, expression)| format!("{name}: ({expression})"))
                .collect::<Vec<_>>()
                .join(", ");
            props.push(format!("values={{{{ {values} }}}}"));
        }
        if !components.is_empty() {
            let values = components
                .iter()
                .map(|(name, expression)| format!("{name}: {expression}"))
                .collect::<Vec<_>>()
                .join(", ");
            props.push(format!("components={{{{ {values} }}}}"));
        }
        self.body.append_at(
            &format!("<__PalamedesTrans {} />", props.join(" ")),
            source_offset,
        );
        true
    }

    fn push_message(
        &mut self,
        message: String,
        placeholders: BTreeMap<String, String>,
        source_offset: usize,
    ) -> MessageReference {
        self.push_message_with_runtime(message.clone(), message, placeholders, source_offset)
    }

    fn push_message_with_runtime(
        &mut self,
        message: String,
        runtime_message: String,
        placeholders: BTreeMap<String, String>,
        source_offset: usize,
    ) -> MessageReference {
        let id = compiled_message_key(&message, None);
        if !self.compiled_ids.iter().any(|existing| existing == &id) {
            self.compiled_ids.push(id.clone());
        }
        let (line, column) = self.locator.location(source_offset);
        let comment = preceding_comment(self.source, source_offset, &self.options.ignore_directive);
        self.messages.push(ExtractedMessageRecord {
            message: message.clone(),
            comment,
            context: None,
            placeholders: (!placeholders.is_empty()).then_some(placeholders),
            origin: (self.filename.to_owned(), line, Some(column)),
            scope: None,
        });
        MessageReference {
            message: runtime_message,
            id,
        }
    }

    fn rewrite_jsx_tag(&mut self, range: Range) -> String {
        let source = range_text(self.source, range);
        let mut replacements = Vec::new();
        let ignored = self
            .unit
            .as_ref()
            .and_then(|unit| unit.ignored)
            .unwrap_or_else(|| {
                is_ignored_unit(
                    self.source,
                    range.start_usize(),
                    &self.options.ignore_directive,
                )
            });
        for attribute in static_jsx_attributes(source) {
            if self.options.framework == MdxFramework::React && attribute.name == "class" {
                replacements.push((
                    attribute.name_start,
                    attribute.name_end,
                    "className".to_owned(),
                ));
            }
            if ignored {
                continue;
            }
            if matches!(attribute.name.as_str(), "href" | "src")
                || !self
                    .options
                    .translatable_attributes
                    .iter()
                    .any(|name| name == &attribute.name)
            {
                continue;
            }
            let value = decode_jsx_entities(attribute.value);
            if value.is_empty() {
                continue;
            }
            let reference = self.push_message(
                value,
                BTreeMap::new(),
                range.start_usize() + attribute.value_start,
            );
            self.needs_i18n = true;
            replacements.push((
                attribute.token_start,
                attribute.token_end,
                format!(
                    "{{__palamedesGetI18n()._({})}}",
                    runtime_lookup_arguments(&reference, self.options.keep_source_fallbacks)
                ),
            ));
        }
        let mut output = source.to_owned();
        for (start, end, replacement) in replacements.into_iter().rev() {
            output.replace_range(start..end, &replacement);
        }
        output
    }
}

#[derive(Default)]
struct RichUnit {
    roots: Vec<RichNode>,
    frames: Vec<RichFrame>,
    values: BTreeMap<String, String>,
    used_names: BTreeSet<String>,
    source_offset: Option<usize>,
    ignored: Option<bool>,
    body_checkpoint: WriterCheckpoint,
}

impl RichUnit {
    fn new(body_checkpoint: WriterCheckpoint) -> Self {
        Self {
            body_checkpoint,
            ..Self::default()
        }
    }

    fn push(&mut self, node: RichNode) {
        if self.source_offset.is_none() {
            self.source_offset = node.source_offset();
        }
        match self.frames.last_mut() {
            Some(RichFrame::Component(component)) => component.children.push(node),
            Some(RichFrame::Transparent(children)) => children.push(node),
            Some(RichFrame::Image(image)) => image.children.push(node),
            None => self.roots.push(node),
        }
    }

    fn text(&mut self, source: &str, range: Range) {
        let raw = range_text(source, range);
        if is_html_comment(raw) {
            return;
        }
        let text = clean_jsx_text(raw);
        if !text.is_empty() {
            self.push(RichNode::Text(text, Some(range.start_usize())));
        }
    }

    fn value(&mut self, expression: &str, source_offset: usize) {
        if let Some(name) = self
            .values
            .iter()
            .find(|(_, existing)| existing.as_str() == expression)
            .map(|(name, _)| name.clone())
        {
            self.push(RichNode::Value {
                name,
                expression: expression.to_owned(),
                source_offset,
            });
            return;
        }
        let base = infer_expression_name(expression);
        let name = unique_name(&base, &mut self.used_names);
        self.values.insert(name.clone(), expression.to_owned());
        self.push(RichNode::Value {
            name,
            expression: expression.to_owned(),
            source_offset,
        });
    }

    fn open_component(&mut self, opening: String, closing: String, source_offset: usize) {
        if self.source_offset.is_none() && source_offset > 0 {
            self.source_offset = Some(source_offset);
        }
        self.frames.push(RichFrame::Component(RichComponent {
            opening,
            closing,
            children: Vec::new(),
            source_offset,
            fixed: false,
        }));
    }

    fn open_transparent(&mut self) {
        self.frames.push(RichFrame::Transparent(Vec::new()));
    }

    fn open_image(&mut self, src: String, source_offset: usize) {
        self.frames.push(RichFrame::Image(RichImage {
            src,
            children: Vec::new(),
            source_offset,
        }));
    }

    fn close_frame(&mut self) {
        let Some(frame) = self.frames.pop() else {
            return;
        };
        match frame {
            RichFrame::Component(component) => self.push(RichNode::Component(component)),
            RichFrame::Transparent(children) => {
                for child in children {
                    self.push(child);
                }
            }
            RichFrame::Image(image) => {
                self.frames.push(RichFrame::Image(image));
            }
        }
    }

    fn close_image(&mut self) -> Option<RichImage> {
        match self.frames.pop() {
            Some(RichFrame::Image(image)) => Some(image),
            Some(other) => {
                self.frames.push(other);
                None
            }
            None => None,
        }
    }

    fn close_all(&mut self) {
        while !self.frames.is_empty() {
            if matches!(self.frames.last(), Some(RichFrame::Image(_))) {
                let image = match self.frames.pop() {
                    Some(RichFrame::Image(image)) => image,
                    _ => unreachable!(),
                };
                let alt = plain_text(&image.children);
                self.push(RichNode::fixed(
                    format!(
                        "<img src={{{}}} alt={{{}}} />",
                        js_string(&image.src),
                        js_string(&alt)
                    ),
                    image.source_offset,
                ));
            } else {
                self.close_frame();
            }
        }
    }
}

enum RichFrame {
    Component(RichComponent),
    Transparent(Vec<RichNode>),
    Image(RichImage),
}

struct RichImage {
    src: String,
    children: Vec<RichNode>,
    source_offset: usize,
}

enum RichNode {
    Text(String, Option<usize>),
    Value {
        name: String,
        expression: String,
        source_offset: usize,
    },
    Component(RichComponent),
}

impl RichNode {
    fn fixed(markup: String, source_offset: usize) -> Self {
        Self::Component(RichComponent {
            opening: markup,
            closing: String::new(),
            children: Vec::new(),
            source_offset,
            fixed: true,
        })
    }

    fn source_offset(&self) -> Option<usize> {
        match self {
            Self::Text(_, offset) => *offset,
            Self::Value { source_offset, .. } => Some(*source_offset),
            Self::Component(component) => Some(component.source_offset),
        }
    }
}

struct RichComponent {
    opening: String,
    closing: String,
    children: Vec<RichNode>,
    source_offset: usize,
    fixed: bool,
}

#[derive(Clone, Copy)]
enum IcuLiteralTarget {
    Catalog,
    Runtime,
}

impl IcuLiteralTarget {
    fn escape(self, text: &str) -> String {
        match self {
            Self::Catalog => text.to_owned(),
            Self::Runtime => escape_icu_literal(text),
        }
    }
}

fn rich_message(
    nodes: &[RichNode],
    framework: MdxFramework,
    target: IcuLiteralTarget,
    collect_components: bool,
    next_component: &mut usize,
    components: &mut Vec<(String, String)>,
) -> crate::jsx_message::JoinedJsxMessage {
    let mut parts = Vec::new();
    for node in nodes {
        match node {
            RichNode::Text(text, _) => {
                parts.push(JsxMessagePart::Text(target.escape(text)));
            }
            RichNode::Value { name, .. } => {
                parts.push(JsxMessagePart::ValuePlaceholder(format!("{{{name}}}")));
            }
            RichNode::Component(component) => {
                let name = next_component.to_string();
                *next_component += 1;
                let joined = rich_message(
                    &component.children,
                    framework,
                    target,
                    collect_components,
                    next_component,
                    components,
                );
                let is_empty = component.fixed || joined.message.is_empty();
                let value = if is_empty {
                    format!("<{name}/>")
                } else {
                    format!("<{name}>{}</{name}>", joined.message)
                };
                parts.push(JsxMessagePart::ComponentPlaceholder { value, is_empty });
                if collect_components {
                    let expression = component_expression(component, framework);
                    components.push((name, expression));
                }
            }
        }
    }
    let mut joined = join_jsx_message_parts(&parts);
    if matches!(target, IcuLiteralTarget::Catalog) {
        joined.message = escape_icu_source_literal(&joined.message);
    }
    joined
}

fn component_expression(component: &RichComponent, framework: MdxFramework) -> String {
    if component.fixed {
        return component.opening.clone();
    }
    match framework {
        MdxFramework::React => opening_to_self_closing(&component.opening),
        MdxFramework::Solid => format!(
            "(children) => {}{{children}}{}",
            component.opening, component.closing
        ),
    }
}

fn opening_to_self_closing(opening: &str) -> String {
    let trimmed = opening.trim();
    if trimmed.ends_with("/>") {
        return trimmed.to_owned();
    }
    trimmed
        .strip_suffix('>')
        .map_or_else(|| format!("{trimmed} />"), |prefix| format!("{prefix} />"))
}

fn fallback_jsx(nodes: &[RichNode]) -> String {
    let mut output = String::new();
    for node in nodes {
        match node {
            RichNode::Text(text, _) => output.push_str(&format!("{{{}}}", js_string(text))),
            RichNode::Value { expression, .. } => {
                output.push('{');
                output.push_str(expression);
                output.push('}');
            }
            RichNode::Component(component) => {
                output.push_str(&component.opening);
                if !component.fixed {
                    output.push_str(&fallback_jsx(&component.children));
                    output.push_str(&component.closing);
                }
            }
        }
    }
    output
}

fn plain_text(nodes: &[RichNode]) -> String {
    let mut text = String::new();
    for node in nodes {
        match node {
            RichNode::Text(value, _) => text.push_str(value),
            RichNode::Value { .. } => {}
            RichNode::Component(component) => text.push_str(&plain_text(&component.children)),
        }
    }
    clean_jsx_text(&text)
}

fn infer_expression_name(expression: &str) -> String {
    let expression = expression.trim().trim_matches('(').trim_matches(')');
    let candidate = expression
        .strip_suffix("()")
        .unwrap_or(expression)
        .rsplit(['.', '['])
        .next()
        .unwrap_or("value")
        .trim_end_matches(']')
        .trim_matches(|character: char| {
            !character.is_ascii_alphanumeric() && character != '_' && character != '$'
        });
    let candidate = candidate.strip_prefix("get").and_then(|suffix| {
        let first = suffix.chars().next()?;
        first.is_ascii_uppercase().then(|| {
            let mut value = first.to_ascii_lowercase().to_string();
            value.push_str(&suffix[first.len_utf8()..]);
            value
        })
    });
    let candidate = candidate
        .as_deref()
        .unwrap_or(candidate_or_value(expression));
    if is_js_identifier(candidate) {
        candidate.to_owned()
    } else {
        "value".to_owned()
    }
}

fn candidate_or_value(expression: &str) -> &str {
    let candidate = expression
        .rsplit(['.', '['])
        .next()
        .unwrap_or("value")
        .trim_end_matches(']')
        .trim_matches(|character: char| {
            !character.is_ascii_alphanumeric() && character != '_' && character != '$'
        });
    if candidate.is_empty() {
        "value"
    } else {
        candidate
    }
}

fn unique_name(base: &str, used: &mut BTreeSet<String>) -> String {
    if used.insert(base.to_owned()) {
        return base.to_owned();
    }
    let mut suffix = 1usize;
    loop {
        let candidate = format!("{base}_{suffix}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
        suffix += 1;
    }
}

fn is_js_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first.is_ascii_alphabetic() || matches!(first, '_' | '$'))
        && chars
            .all(|character| character.is_ascii_alphanumeric() || matches!(character, '_' | '$'))
}

fn range_text(source: &str, range: Range) -> &str {
    range
        .slice_str(source.as_bytes())
        .expect("FerroMark ranges must retain UTF-8 boundaries")
}

fn js_string(value: &str) -> String {
    serde_json::to_string(value).expect("string must serialize")
}

fn is_jsx_comment(value: &str) -> bool {
    let trimmed = value.trim();
    trimmed.starts_with("{/*") && trimmed.ends_with("*/}")
}

fn is_html_comment(value: &str) -> bool {
    let trimmed = value.trim();
    trimmed.starts_with("<!--") && trimmed.ends_with("-->")
}

fn is_ignored_unit(source: &str, offset: usize, directive: &str) -> bool {
    preceding_comment_payload(source, offset).is_some_and(|comment| comment.contains(directive))
}

fn preceding_comment(source: &str, offset: usize, directive: &str) -> Option<String> {
    let comment = preceding_comment_payload(source, offset)?.trim();
    (!comment.is_empty() && !comment.contains(directive)).then(|| comment.to_owned())
}

fn preceding_comment_payload(source: &str, offset: usize) -> Option<&str> {
    let prefix = &source[..offset.min(source.len())];
    let completed_lines = prefix.rsplit_once('\n').map_or("", |(lines, _)| lines);
    let trimmed = completed_lines.trim_end();
    if let Some(before_end) = trimmed.strip_suffix("*/}") {
        if let Some(start) = before_end.rfind("{/*") {
            return Some(&before_end[start + 3..]);
        }
    }
    if let Some(before_end) = trimmed.strip_suffix("-->") {
        if let Some(start) = before_end.rfind("<!--") {
            return Some(&before_end[start + 4..]);
        }
    }
    trimmed
        .lines()
        .next_back()
        .and_then(|line| line.trim().strip_prefix("//"))
}

fn unsupported_footnote_range(source: &str, events: &[MdxEvent]) -> Option<Range> {
    let mut exact_range = None;
    let mut has_reference = false;
    for event in events {
        match event {
            MdxEvent::Inline(InlineEvent::FootnoteRef { .. }) => has_reference = true,
            MdxEvent::Inline(InlineEvent::InlineFootnote(range)) => {
                exact_range = Some(*range);
                break;
            }
            _ => {}
        }
    }
    exact_range.or_else(|| {
        (has_reference || source.contains("[^"))
            .then(|| find_footnote_reference(source))
            .flatten()
    })
}

fn find_footnote_reference(source: &str) -> Option<Range> {
    let mut offset = 0usize;
    let mut fence = None;
    for line in source.split_inclusive('\n') {
        let content = line.trim_end_matches(['\r', '\n']);
        let trimmed = content.trim_start();
        let indentation = content.len().saturating_sub(trimmed.len());
        let marker = (indentation <= 3)
            .then(|| trimmed.as_bytes().first().copied())
            .flatten()
            .filter(|_| trimmed.len() >= 3)
            .filter(|byte| matches!(byte, b'`' | b'~'))
            .filter(|byte| {
                trimmed
                    .as_bytes()
                    .iter()
                    .take(3)
                    .all(|candidate| candidate == byte)
            });
        if let Some(marker) = marker {
            if fence == Some(marker) {
                fence = None;
            } else if fence.is_none() {
                fence = Some(marker);
            }
            offset += line.len();
            continue;
        }
        if fence.is_some() {
            offset += line.len();
            continue;
        }

        let bytes = content.as_bytes();
        let mut position = 0usize;
        let mut inline_code = false;
        while position + 2 < bytes.len() {
            if bytes[position] == b'`' {
                inline_code = !inline_code;
                position += 1;
                continue;
            }
            if inline_code || bytes[position] != b'[' || bytes[position + 1] != b'^' {
                position += 1;
                continue;
            }
            let escaped = bytes[..position]
                .iter()
                .rev()
                .take_while(|byte| **byte == b'\\')
                .count()
                % 2
                == 1;
            if escaped {
                position += 2;
                continue;
            }
            let Some(relative_end) = bytes[position + 2..].iter().position(|byte| *byte == b']')
            else {
                break;
            };
            let end = position + 2 + relative_end;
            return Some(Range::from_usize(offset + position, offset + end + 1));
        }
        offset += line.len();
    }
    None
}

struct FrontMatterScalar {
    key: String,
    value: String,
    value_offset: usize,
}

fn parse_front_matter_scalars(source: &str, content: Range) -> Vec<FrontMatterScalar> {
    let raw = range_text(source, content);
    let mut scalars = Vec::new();
    let mut local_offset = 0usize;
    for line in raw.split_inclusive('\n') {
        let line_without_end = line.trim_end_matches(['\r', '\n']);
        let Some((key, value, separator_offset)) = split_front_matter_scalar(line_without_end)
        else {
            local_offset += line.len();
            continue;
        };
        let value_trimmed = value.trim();
        let leading = value.len() - value.trim_start().len();
        let quoted = value_trimmed
            .strip_prefix('"')
            .and_then(|value| value.strip_suffix('"'))
            .or_else(|| {
                value_trimmed
                    .strip_prefix('\'')
                    .and_then(|value| value.strip_suffix('\''))
            });
        if quoted.is_none()
            && matches!(
                value_trimmed.as_bytes().first(),
                Some(b'[' | b'{' | b'|' | b'>')
            )
        {
            local_offset += line.len();
            continue;
        }
        let unquoted = quoted.unwrap_or(value_trimmed);
        if !key.is_empty() && !unquoted.is_empty() {
            scalars.push(FrontMatterScalar {
                key: key.to_owned(),
                value: unquoted.to_owned(),
                value_offset: content.start_usize()
                    + local_offset
                    + separator_offset
                    + 1
                    + leading
                    + usize::from(value_trimmed.starts_with(['"', '\''])),
            });
        }
        local_offset += line.len();
    }
    scalars
}

fn split_front_matter_scalar(line: &str) -> Option<(&str, &str, usize)> {
    let separator = line.find([':', '='])?;
    let key = line[..separator].trim();
    if key.is_empty() || key.contains(char::is_whitespace) {
        return None;
    }
    Some((key, &line[separator + 1..], separator))
}

struct StaticJsxAttribute<'a> {
    name: String,
    name_start: usize,
    name_end: usize,
    value: &'a str,
    value_start: usize,
    token_start: usize,
    token_end: usize,
}

fn static_jsx_attributes(source: &str) -> Vec<StaticJsxAttribute<'_>> {
    let bytes = source.as_bytes();
    if bytes.first() != Some(&b'<') || bytes.get(1) == Some(&b'/') {
        return Vec::new();
    }
    let mut position = 1usize;
    while matches!(
        bytes.get(position),
        Some(byte) if byte.is_ascii_alphanumeric() || matches!(*byte, b'_' | b'-' | b'.' | b':')
    ) {
        position += 1;
    }
    let mut attributes = Vec::new();
    while position < bytes.len() {
        while matches!(bytes.get(position), Some(byte) if byte.is_ascii_whitespace()) {
            position += 1;
        }
        if matches!(bytes.get(position), Some(b'>') | Some(b'/')) {
            break;
        }
        if bytes.get(position) == Some(&b'{') {
            let Some(length) = ferromark::mdx::expr::find_expression_end(&bytes[position..]) else {
                break;
            };
            position += length;
            continue;
        }
        let name_start = position;
        while matches!(
            bytes.get(position),
            Some(byte) if byte.is_ascii_alphanumeric() || matches!(*byte, b'_' | b'-' | b'.' | b':')
        ) {
            position += 1;
        }
        if position == name_start {
            break;
        }
        let name_end = position;
        let name = source[name_start..position].to_owned();
        while matches!(bytes.get(position), Some(byte) if byte.is_ascii_whitespace()) {
            position += 1;
        }
        if bytes.get(position) != Some(&b'=') {
            continue;
        }
        position += 1;
        while matches!(bytes.get(position), Some(byte) if byte.is_ascii_whitespace()) {
            position += 1;
        }
        let token_start = position;
        let Some(quote @ (b'"' | b'\'')) = bytes.get(position).copied() else {
            if bytes.get(position) == Some(&b'{') {
                let Some(length) = ferromark::mdx::expr::find_expression_end(&bytes[position..])
                else {
                    break;
                };
                position += length;
            } else {
                while matches!(
                    bytes.get(position),
                    Some(byte) if !byte.is_ascii_whitespace() && !matches!(*byte, b'>' | b'/')
                ) {
                    position += 1;
                }
            }
            continue;
        };
        position += 1;
        let value_start = position;
        while position < bytes.len() && bytes[position] != quote {
            if bytes[position] == b'\\' {
                position = (position + 2).min(bytes.len());
            } else {
                position += 1;
            }
        }
        if position >= bytes.len() {
            break;
        }
        let value_end = position;
        position += 1;
        attributes.push(StaticJsxAttribute {
            name,
            name_start,
            name_end,
            value: &source[value_start..value_end],
            value_start,
            token_start,
            token_end: position,
        });
    }
    attributes
}

#[derive(Clone, Copy, Debug)]
struct SourceAnchor {
    generated_line: usize,
    generated_column: usize,
    source_offset: usize,
}

#[derive(Clone, Copy, Debug, Default)]
struct WriterCheckpoint {
    code_len: usize,
    anchor_len: usize,
}

#[derive(Default)]
struct ModuleWriter {
    code: String,
    anchors: Vec<SourceAnchor>,
}

impl ModuleWriter {
    fn checkpoint(&self) -> WriterCheckpoint {
        WriterCheckpoint {
            code_len: self.code.len(),
            anchor_len: self.anchors.len(),
        }
    }

    fn restore(&mut self, checkpoint: WriterCheckpoint) {
        self.code.truncate(checkpoint.code_len);
        self.anchors.truncate(checkpoint.anchor_len);
    }

    fn append(&mut self, value: &str) {
        self.code.push_str(value);
    }

    fn append_at(&mut self, value: &str, source_offset: usize) {
        let (generated_line, generated_column) = generated_position(&self.code);
        self.anchors.push(SourceAnchor {
            generated_line,
            generated_column,
            source_offset,
        });
        self.code.push_str(value);
    }

    fn append_writer(&mut self, writer: &Self, indent: &str) {
        let target_line_base = generated_position(&self.code).0;
        for line in writer.code.split_inclusive('\n') {
            if !line.is_empty() {
                self.code.push_str(indent);
            }
            self.code.push_str(line);
        }
        for anchor in &writer.anchors {
            self.anchors.push(SourceAnchor {
                generated_line: target_line_base + anchor.generated_line,
                generated_column: anchor.generated_column + indent.encode_utf16().count(),
                source_offset: anchor.source_offset,
            });
        }
    }
}

fn generated_position(source: &str) -> (usize, usize) {
    let line = source.bytes().filter(|byte| *byte == b'\n').count();
    let column_source = source.rsplit_once('\n').map_or(source, |(_, tail)| tail);
    (line, column_source.encode_utf16().count())
}

fn source_position_utf16(source: &str, offset: usize) -> (usize, usize) {
    let prefix = &source[..offset.min(source.len())];
    let line = prefix.bytes().filter(|byte| *byte == b'\n').count();
    let line_source = prefix.rsplit_once('\n').map_or(prefix, |(_, tail)| tail);
    (line, line_source.encode_utf16().count())
}

fn encode_mappings(anchors: &[SourceAnchor], source: &str) -> String {
    if anchors.is_empty() {
        return String::new();
    }
    let mut anchors = anchors.to_vec();
    anchors.sort_by_key(|anchor| (anchor.generated_line, anchor.generated_column));
    anchors.dedup_by_key(|anchor| (anchor.generated_line, anchor.generated_column));
    let max_line = anchors
        .iter()
        .map(|anchor| anchor.generated_line)
        .max()
        .unwrap_or(0);
    let mut output = String::new();
    let mut index = 0usize;
    let mut previous_source = 0i64;
    let mut previous_original_line = 0i64;
    let mut previous_original_column = 0i64;
    for line in 0..=max_line {
        if line > 0 {
            output.push(';');
        }
        let mut previous_generated_column = 0i64;
        let mut first_segment = true;
        while let Some(anchor) = anchors
            .get(index)
            .filter(|anchor| anchor.generated_line == line)
        {
            if !first_segment {
                output.push(',');
            }
            first_segment = false;
            vlq(
                anchor.generated_column as i64 - previous_generated_column,
                &mut output,
            );
            previous_generated_column = anchor.generated_column as i64;
            vlq(-previous_source, &mut output);
            previous_source = 0;
            let (source_line, source_column) = source_position_utf16(source, anchor.source_offset);
            vlq(source_line as i64 - previous_original_line, &mut output);
            previous_original_line = source_line as i64;
            vlq(source_column as i64 - previous_original_column, &mut output);
            previous_original_column = source_column as i64;
            index += 1;
        }
    }
    output
}

fn vlq(value: i64, output: &mut String) {
    const BASE64: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut value = if value < 0 {
        ((-value) as u64) << 1 | 1
    } else {
        (value as u64) << 1
    };
    loop {
        let mut digit = (value & 31) as usize;
        value >>= 5;
        if value > 0 {
            digit |= 32;
        }
        output.push(char::from(BASE64[digit]));
        if value == 0 {
            break;
        }
    }
}

#[cfg(test)]
mod tests {
    use oxc_allocator::Allocator;
    use oxc_parser::Parser;
    use oxc_span::SourceType;

    use super::*;

    fn messages(source: &str) -> Vec<String> {
        analyze_valid(source, MdxOptions::default())
            .messages
            .into_iter()
            .map(|message| message.message)
            .collect()
    }

    fn analyze_valid(source: &str, options: MdxOptions) -> MdxAnalysisResult {
        let result = analyze_mdx(source, "guide.mdx", options);
        assert!(
            result.diagnostics.is_empty(),
            "valid fixture produced diagnostics: {:?}",
            result.diagnostics
        );
        assert_valid_tsx(result.code.as_deref().expect("valid MDX should compile"));
        result
    }

    #[test]
    fn extracts_semantic_units_and_protects_non_prose() {
        let source = r#"import { Card } from "./Card"

# Hello {name}

Read [the guide](https://example.com) and `npm test`.

- First item
- Second **important** item

```ts
const untranslated = "code";
```
"#;
        assert_eq!(
            messages(source),
            [
                "Hello {name}",
                "Read <0>the guide</0> and <1/>.",
                "First item",
                "Second <0>important</0> item",
            ]
        );
        let result = analyze_valid(source, MdxOptions::default());
        let code = result.code.expect("valid MDX should compile");
        assert!(code.contains("import { Card } from \"./Card\""));
        assert!(code.contains("<__PalamedesTrans"));
        assert!(code.contains(r#"<pre><code className={"language-ts"}>"#));
        assert!(result.map.is_some());
    }

    #[test]
    fn separates_mdx_catalog_apostrophes_from_runtime_escaping() {
        let result = analyze_valid(
            "don't client's l'été It''s L'{title}",
            MdxOptions {
                keep_source_fallbacks: true,
                ..MdxOptions::default()
            },
        );
        assert_eq!(
            result
                .messages
                .iter()
                .map(|message| message.message.as_str())
                .collect::<Vec<_>>(),
            ["don't client's l'été It''s L''{title}"]
        );
        assert_eq!(
            result.compiled_ids,
            [compiled_message_key(
                "don't client's l'été It''s L''{title}",
                None,
            )]
        );
        let code = result.code.expect("valid MDX should compile");
        assert!(
            code.contains("don''t client''s l''été It''s L''{title}"),
            "runtime message must escape natural apostrophes without re-doubling pairs:\n{code}"
        );
    }

    #[test]
    fn extracts_blockquotes_tables_and_image_alt_at_source_locations() {
        let source = r#"> A quoted paragraph.

| Name | Meaning |
| --- | --- |
| Alpha | First |

![Diagram label](./diagram.png)
"#;
        let result = analyze_valid(source, MdxOptions::default());
        assert_eq!(
            result
                .messages
                .iter()
                .map(|message| (message.message.as_str(), message.origin.1))
                .collect::<Vec<_>>(),
            [
                ("A quoted paragraph.", 1),
                ("Name", 3),
                ("Meaning", 3),
                ("Alpha", 5),
                ("First", 5),
                ("Diagram label", 7),
            ]
        );
    }

    #[test]
    fn extracts_images_attributes_front_matter_and_honors_ignore() {
        let source = r#"---
title: Welcome
slug: welcome
tags: [docs, mdx]
---

![An example](./example.png)

<Card title="Open settings">Read this</Card>

{/* palamedes-ignore */}

Do not translate this.
"#;
        let result = analyze_valid(
            source,
            MdxOptions {
                translatable_attributes: vec!["alt".to_owned(), "title".to_owned()],
                front_matter_fields: vec!["title".to_owned()],
                ..MdxOptions::default()
            },
        );
        let extracted = result
            .messages
            .iter()
            .map(|message| message.message.as_str())
            .collect::<Vec<_>>();
        assert!(extracted.contains(&"Welcome"));
        assert!(extracted.contains(&"An example"));
        assert!(extracted.contains(&"Open settings"));
        assert!(extracted.contains(&"<0>Read this</0>"));
        assert!(!extracted.contains(&"Do not translate this."));
        let code = result.code.expect("valid MDX should compile");
        assert!(code.contains("getTranslatedFrontmatter"));
        assert!(!code.contains(r#""tags""#));
    }

    #[test]
    fn returns_source_ranged_structural_diagnostics() {
        let result = analyze_mdx(
            "# Good\n\n<Component\n",
            "broken.mdx",
            MdxOptions::default(),
        );
        assert!(result.code.is_none());
        assert!(!result.diagnostics.is_empty());
        assert_eq!(result.diagnostics[0].primary.line, 3);
    }

    #[test]
    fn react_and_solid_use_their_runtime_component_contracts() {
        let source = "Hello **world**.";
        let react = analyze_valid(source, MdxOptions::default())
            .code
            .expect("React compile");
        assert!(react.contains(r#"from "@palamedes/react/compiled""#));
        assert!(react.contains("0: <strong />"));

        let solid = analyze_valid(
            source,
            MdxOptions {
                framework: MdxFramework::Solid,
                ..MdxOptions::default()
            },
        )
        .code
        .expect("Solid compile");
        assert!(solid.contains(r#"from "@palamedes/solid/compiled""#));
        assert!(solid.contains("0: (children) => <strong>{children}</strong>"));
    }

    #[test]
    fn strips_runtime_source_fallbacks_by_default_and_can_preserve_them() {
        let source = r#"---
title: Front matter fallback
---

Visible fallback phrase.

![Image fallback phrase](./diagram.png)

<Card title="Attribute fallback phrase" />
"#;
        let options = MdxOptions {
            translatable_attributes: vec!["alt".to_owned(), "title".to_owned()],
            front_matter_fields: vec!["title".to_owned()],
            ..MdxOptions::default()
        };
        let stripped = analyze_valid(source, options.clone())
            .code
            .expect("stripped compile");
        let kept = analyze_valid(
            source,
            MdxOptions {
                keep_source_fallbacks: true,
                ..options
            },
        )
        .code
        .expect("fallback-preserving compile");

        assert!(!stripped.contains("message={"));
        assert!(!stripped.contains("{ message:"));
        assert!(kept.contains("message={\"Visible fallback phrase.\"}"));
        assert!(kept.contains("{ message: \"Image fallback phrase\" }"));
        assert!(kept.contains("{ message: \"Attribute fallback phrase\" }"));
        assert!(kept.contains("{ message: \"Front matter fallback\" }"));
    }

    #[test]
    fn directive_text_is_translatable_and_ignore_covers_inline_records() {
        let prose = "Use the palamedes-ignore comment to opt out.";
        assert_eq!(messages(prose), [prose]);

        let source = r#"{/* palamedes-ignore */}

See ![Diagram label](./d.png) here.

{/* palamedes-ignore */}

<Card title="Open settings" />
"#;
        let result = analyze_valid(
            source,
            MdxOptions {
                translatable_attributes: vec!["alt".to_owned(), "title".to_owned()],
                ..MdxOptions::default()
            },
        );
        assert!(result.messages.is_empty());
        let code = result.code.expect("valid MDX should compile");
        assert!(code.contains(r#"alt={"Diagram label"}"#));
        assert!(code.contains(r#"title="Open settings""#));
        assert!(!code.contains("__palamedesGetI18n"));
    }

    #[test]
    fn string_attributes_use_expression_containers() {
        let source =
            "Read [the guide](<https://x.test/a\"b>).\n\n![A \"quoted\" label](./a\"b.png)";
        let result = analyze_valid(source, MdxOptions::default());
        let code = result.code.expect("valid MDX should compile");
        assert!(code.contains(r#"href={"https://x.test/a\"b"}"#));
        assert!(code.contains(r#"src={"./a\"b.png"}"#));
    }

    #[test]
    fn comments_are_metadata_instead_of_visible_messages() {
        let html_source = "<!-- Translator: keep short -->\n\nSave now.";
        let html = analyze_valid(html_source, MdxOptions::default());
        assert_eq!(
            html.messages
                .iter()
                .map(|message| (message.message.as_str(), message.comment.as_deref()))
                .collect::<Vec<_>>(),
            [("Save now.", Some("Translator: keep short"))]
        );
        assert!(!html
            .code
            .expect("valid MDX should compile")
            .contains("<!-- Translator"));

        let jsx_source = "{/* Keep the product name */}\n\nWelcome to Palamedes.";
        let jsx = analyze_valid(jsx_source, MdxOptions::default());
        assert_eq!(
            jsx.messages[0].comment.as_deref(),
            Some("Keep the product name")
        );
    }

    #[test]
    fn rejects_footnotes_with_a_source_ranged_diagnostic() {
        let result = analyze_mdx(
            "Text with a note[^1].\n\n[^1]: The note body.",
            "guide.mdx",
            MdxOptions::default(),
        );
        assert!(result.code.is_none());
        assert_eq!(result.diagnostics.len(), 1);
        assert_eq!(result.diagnostics[0].code, "UnsupportedFootnote");
        assert_eq!(result.diagnostics[0].primary.line, 1);
        assert_eq!(result.diagnostics[0].primary.column, 17);

        let definition_only =
            analyze_mdx("[^1]: The note body.", "guide.mdx", MdxOptions::default());
        assert_eq!(definition_only.diagnostics[0].code, "UnsupportedFootnote");

        analyze_valid(
            "Use `[^label]` in prose.\n\n```md\n[^label]: code sample\n```",
            MdxOptions::default(),
        );
    }

    #[test]
    fn deduplicates_expressions_and_preserves_rendering_metadata() {
        let source = "Hello {user.name} and again {user.name}.\n\n```ts\nconst value = 1\n```\n\n<div class=\"note\">Styled</div>";
        let result = analyze_valid(source, MdxOptions::default());
        assert_eq!(result.messages[0].message, "Hello {name} and again {name}.");
        assert_eq!(
            result.messages[0]
                .placeholders
                .as_ref()
                .expect("expression placeholders")
                .len(),
            1
        );
        let code = result.code.expect("valid MDX should compile");
        assert!(code.contains(r#"className={"language-ts"}"#));
        assert!(
            code.contains(r#"<div className="note" />"#),
            "generated module should normalize React class attributes:\n{code}"
        );
    }

    fn assert_valid_tsx(source: &str) {
        let allocator = Allocator::default();
        let parsed = Parser::new(&allocator, source, SourceType::tsx()).parse();
        assert!(
            parsed.diagnostics.is_empty(),
            "generated module must be valid TSX: {:?}\n{source}",
            parsed.diagnostics
        );
    }
}
