declare module "virtual:palamedes/server-catalogs" {
  import type { CompiledCatalogMessages } from "@palamedes/core";

  /** Generated by @palamedes/vite-plugin; applications do not implement this. */
  export function loadServerCatalog(locale: string): Promise<CompiledCatalogMessages>;
}
